// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"palikka-go/repository/sqlite/types"
)

type Permission struct {
	ID     int64
	Name   string
	RoleID *int64
}

type Role struct {
	ID   int64
	Name string
	Rank int64
}

type RoleView struct {
	ID               int64
	Name             string
	Rank             int64
	PermissionID     *int64
	PermissionName   *string
	PermissionRoleID *int64
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt string
	Active    types.Bool
	RoleID    *int64
}
