// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permission.sql

package sqlc

import (
	"context"
)

const DeletePermissions = `-- name: DeletePermissions :exec
delete from permission where id > 0
`

func (q *Queries) DeletePermissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeletePermissions)
	return err
}

const FindPermissions = `-- name: FindPermissions :many
select p.id, p.name, p.role_id
from permission p
limit ?2
offset ?1
`

type FindPermissionsParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) FindPermissions(ctx context.Context, arg FindPermissionsParams) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, FindPermissions, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindPermissionsByRoleID = `-- name: FindPermissionsByRoleID :many
select p.id, p.name, p.role_id
from permission p
join role r on r.id = p.role_id
where r.rank <= (
    select rr.rank from role rr
    where rr.id = ?1
)
`

func (q *Queries) FindPermissionsByRoleID(ctx context.Context, roleID int64) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, FindPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertPermission = `-- name: InsertPermission :one
insert into permission (name, role_id)
values (?1, ?2)
returning id
`

type InsertPermissionParams struct {
	Name   string
	RoleID *int64
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertPermission, arg.Name, arg.RoleID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const UpdatePermission = `-- name: UpdatePermission :exec
update permission
set role_id = ?1
where id = ?2
`

type UpdatePermissionParams struct {
	RoleID *int64
	ID     int64
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePermission, arg.RoleID, arg.ID)
	return err
}
