// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeletePermissions(ctx context.Context) error
	FindPermissions(ctx context.Context, arg FindPermissionsParams) ([]Permission, error)
	FindPermissionsByRoleID(ctx context.Context, roleID int64) ([]Permission, error)
	FindRoleByID(ctx context.Context, id int64) ([]RoleView, error)
	FindRoles(ctx context.Context) ([]RoleView, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
	FindUsers(ctx context.Context, arg FindUsersParams) ([]User, error)
	InsertPermission(ctx context.Context, arg InsertPermissionParams) (int64, error)
	InsertRole(ctx context.Context, arg InsertRoleParams) (int64, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
