// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package sqlc

import (
	"context"
)

const FindRoleByID = `-- name: FindRoleByID :many
select id, name, rank, permission_id, permission_name, permission_role_id from role_view where id = ?1
`

func (q *Queries) FindRoleByID(ctx context.Context, id int64) ([]RoleView, error) {
	rows, err := q.db.QueryContext(ctx, FindRoleByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleView
	for rows.Next() {
		var i RoleView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionRoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindRoles = `-- name: FindRoles :many
select id, name, rank, permission_id, permission_name, permission_role_id from role_view order by id
`

func (q *Queries) FindRoles(ctx context.Context) ([]RoleView, error) {
	rows, err := q.db.QueryContext(ctx, FindRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleView
	for rows.Next() {
		var i RoleView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionRoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertRole = `-- name: InsertRole :one
insert into role (name, rank)
values (?1, ?2)
returning id
`

type InsertRoleParams struct {
	Name string
	Rank int64
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertRole, arg.Name, arg.Rank)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const UpdateRole = `-- name: UpdateRole :exec
update role
set name = ?1,
    rank = ?2
where id = ?3
`

type UpdateRoleParams struct {
	Name string
	Rank int64
	ID   int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, UpdateRole, arg.Name, arg.Rank, arg.ID)
	return err
}
