// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"

	"palikka-go/repository/sqlite/types"
)

const FindUserByID = `-- name: FindUserByID :one
select u.id, u.username, u.password, u.created_at, u.active, u.role_id
from user u
where u.id = ?
limit 1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, FindUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.Active,
		&i.RoleID,
	)
	return i, err
}

const FindUserByUsername = `-- name: FindUserByUsername :one
select u.id, u.username, u.password, u.created_at, u.active, u.role_id
from user u
where u.username = ?
limit 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, FindUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.Active,
		&i.RoleID,
	)
	return i, err
}

const FindUsers = `-- name: FindUsers :many
select u.id, u.username, u.password, u.created_at, u.active, u.role_id
from user u
limit ?2
offset ?1
`

type FindUsersParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) FindUsers(ctx context.Context, arg FindUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, FindUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.Active,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertUser = `-- name: InsertUser :one
insert into user (username, password, active, role_id)
values (?1, ?2, ?3, ?4)
returning id
`

type InsertUserParams struct {
	Username string
	Password string
	Active   types.Bool
	RoleID   *int64
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertUser,
		arg.Username,
		arg.Password,
		arg.Active,
		arg.RoleID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const UpdateUser = `-- name: UpdateUser :exec
update user
set username = ?1,
    password = ?2,
    active = ?3,
    role_id = ?4
where user.id = ?5
`

type UpdateUserParams struct {
	Username string
	Password string
	Active   types.Bool
	RoleID   *int64
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, UpdateUser,
		arg.Username,
		arg.Password,
		arg.Active,
		arg.RoleID,
		arg.ID,
	)
	return err
}
